// DO NOT EDIT
// This file is autogenerated
// use `pnpm codegen` to update
// If you want to make changes, edit the file scripts/generate-types.ts

// exporting scalars
export * from './scalars/Decimal'

// exporting inputs
export * from './inputs/FilterInputs'

// exporting objects
export * from './objects/Building'
export * from './objects/City'
export * from './objects/Country'
export * from './objects/Organization'
export * from './objects/Person'
export * from './objects/Residence'
export * from './objects/Resident'
export * from './objects/State'
export * from './objects/Staff'

// exporting queries
export * from './queries/city/list'
export * from './queries/residence/list'
export * from './queries/residence/root'
export * from './queries/resident/list'
export * from './queries/resident/root'

// exporting mutations
export * from './mutations/auth/login'
export * from './mutations/auth/refresh'
export * from './mutations/auth/root'
export * from './mutations/residence/create'
export * from './mutations/residence/root'
export * from './mutations/residence/types'
