// DO NOT EDIT
// This file is autogenerated
// use `pnpm codegen` to update
// If you want to make changes, edit the file scripts/generate-types.ts

// exporting scalars
export * from './scalars/Decimal'

// exporting inputs
export * from './inputs/FilterInputs'

// exporting objects
export * from './objects/Institution'

// exporting queries
export * from './queries/institution/list'

// exporting mutations
