// DO NOT EDIT
// This file is autogenerated
// use `pnpm generate` to update
// If you want to make changes, edit the file scripts/generate.ts

// exporting tables
export * from './tables/institution'
export * from './tables/institutionalPlan'
export * from './tables/person'
export * from './tables/user'

// exporting relations
